### ISSUE TITLE
can't use it with "phpstan.phar"?

### ISSUE THREAD

**Issue by voku** [thecodingmachine/phpstan-safe-rule#5]
**install:**
```
composer require thecodingmachine/safe
composer require --dev thecodingmachine/phpstan-safe-rule
```

composer.json:
```
...
    "require": {
		"thecodingmachine/safe": "^0.1.10"
	},
    "require-dev": {
        "thecodingmachine/phpstan-safe-rule": "^0.1.0"
    },
    "replace": {
        "phpstan/phpstan": "0.10.*"
    },
...
```

phpstan.neon:
```
parameters:
    excludes_analyse:
        - vendor/*
        - tests/*
    autoload_files:
        - vendor/composer/autoload.php
includes:
    - vendor/composer/thecodingmachine/phpstan-safe-rule/phpstan-safe-rule.neon
```
PS: without the include phpstan runs as expected

**command:**
```
php7.1 vendor/phar/phpstan_php7_1.phar analyse --level=7 --configuration="phpstan.neon" src
```

**error:**
```
Class TheCodingMachine\Safe\PHPStan\Rules\UseSafeFunctionsRule used in service '163' not found.
```
